version: "3.9"

services:
  spooky:
    build: .
    command: ["generate-readme"]
    environment:
      - SPOOKY_OPENAI_KEY=${SPOOKY_OPENAI_KEY:-}
    volumes:
      - ./:/workspace
    working_dir: /app
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:11434/api/version"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ollama-models:/root/.ollama

volumes:
  ollama-models:
    driver: local
